### ISSUE TITLE
Structure of semgrep rules (message and metadata stored)

### ISSUE THREAD

**Issue by hazanasec** [semgrep/rules-owasp-asvs#4]
Need to agree on a consistent message that gets shown when the rule is triggered.
I started with something like:
```
  message: |
    V6 Stored Cryptography Verification Requirements
    6.2.5 Insecure Algorithm
    https://github.com/OWASP/ASVS/blob/master/4.0/en/0x14-V6-Cryptography.md#v62-algorithms
    ...
    specifically why rule was triggered and suggested fix
```
So overarching verification and title since its short, then added the specific requirement and summarised it as it's a bit too long for a message, then the link to ASVS, then the normal rule message.

**Comment by clintgibler** [comment]
Those are definitely useful attributes to include in rules 👍  I have a few thoughts about this, curious about what you think.

For some of this info it seems like it'd be useful to store in a structured way, not as freeform text inline in the message. This lets AppSec teams consuming the results of running Semgrep (e.g. via JSON) do stats / slice and dice more easily: how many findings do we have for "V6 Crypto" vs "Output Encoding" vs ...?

The official [semgrep-rules](https://github.com/returntocorp/semgrep-rules) repo currently stores CWE and OWASP Top 10 info in separate metadata keys. See [here](https://github.com/returntocorp/semgrep-rules/blob/develop/java/rmi/security/server-dangerous-class-deserialization.yaml) for an example.

I propose something like:

```yaml
rules:
- id: asvs-java-v6-crypto-insecure-algorithm
  severity: WARNING
  languages:
  - java
  metadata:
    asvs:
      section: "V6 Stored Cryptography Verification Requirements"
      control_id: "6.2.5 Insecure Algorithm"
      control_url: "https://github.com/OWASP/ASVS/blob/master/4.0/en/0x14-V6-Cryptography.md#v62-algorithms"
      version: "4"
    references:
    - ...useful links to learn more...
  message: |
     specifically why rule was triggered and suggested fix
  patterns:
    ...
```

We can probably think of better names than `section`, `control_id`, and `control_url`, but the basic idea is to split that info into separate fields rather than having to try to parse it out of free-form text in the message.
